name: passcode_screen
description: A platform agnostic Flutter package for showing passcode input screen, similar to Native iOS. Screen customizable with a colors, sizes, fonts etc.
version: 1.0.2
author: 'xPutnikx <vladimir.hudnitsky@gmail.com>'
homepage: 'https://github.com/xPutnikx/flutter-passcode'

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  assets:
    - images/password_popup.svg